scripts/release: guide user through preparing the release
Instead of just complaining that the release steps haven't been
performed', script/release will now guide the user through them.

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -4,8 +4,19 @@ set -eu
 
 v=$(python3 -c 'from squad.version import __version__ as v; print(v)')
 if git rev-parse --verify --quiet "${v}^{tag}" >/dev/null; then
-    echo "It seems version ${v} has already been released. Aborting"
+    echo "Version ${v} has already been released. Let's prepare a new one"
+    editor squad/version.py
+fi
+
+v=$(python3 -c 'from squad.version import __version__ as v; print(v)')
+if git rev-parse --verify --quiet "${v}^{tag}" >/dev/null; then
+    echo "Version ${v} has already been released. Aborting"
     exit 1
+fi
+
+if ! grep -q "^# $v" CHANGELOG.md; then
+    echo "Let's now document the changes in CHANGELOG.md"
+    editor CHANGELOG.md
 fi
 
 if ! grep -q "^# $v" CHANGELOG.md; then
@@ -13,13 +24,18 @@ if ! grep -q "^# $v" CHANGELOG.md; then
     exit 1
 fi
 
-./manage.py test
-
-# TODO: require all changes committed to git
-if ! git diff-index --quiet --exit-code HEAD --; then
+changed=$(git diff-index --name-only HEAD -- | (grep -v 'CHANGELOG.md\|squad/version.py' || true))
+if [ -n "$changed" ]; then
     echo "E: uncommited changes found; cannot release like this"
+    echo "I: changed files:"
+    echo "$changed"
+    echo "I: CHANGELOG.md and squad/version.py are excused, they would be committed automatically"
     exit 1
 fi
+
+./manage.py test
+
+git commit --message "New release: ${v}" CHANGELOG.md squad/version.py || true
 
 if ! ./scripts/check-ci; then
     printf "Are you sure you want to continue? [y/N]"
